# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1926
          POSTGRES_DB: simple_bank
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: check out code into go module directory
      uses: actions/checkout@v3     

    - name: Run Migration
      run:  migrate -path db/migration -database "postgresql://user_name:password@localhost:5432/db_name?sslmode=disable" -verbose up

    - name : Install go lang migrate
      run: |
       curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
       sudo mv migrate /usr/bin/
       which migrate

    - name: Test
      run: go test  -v -cover ./...
